packages:
  GRPC:
    url: https://github.com/grpc/grpc-swift.git
    version: 1.0.0-alpha.9
name: Echo
configs:
  Debug: debug
  Release: release
options:
  groupSortPosition: top
schemes:
  Echo:
    build:
      targets:
        Echo: all
    run:
      config: Debug
      environmentVariables:
        OS_ACTIVITY_MODE: disable
    test:
      config: Debug
      targets:
        - Echo
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

targets:
  Echo:
    type: application
    platform: iOS
    sources:
      - path: Echo
    dependencies:
      - target: GRPCClient
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: jp.co.cyberagent.GRPCClient.Echo

  GRPCClient:
    type: framework
    platform: iOS
    sources:
      - path: ../../Sources/GRPCClient
    dependencies:
      - package: GRPC
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: jp.co.cyberagent.GRPCClient.Echo.GRPCClient
